Feat/map : 로딩 컴포넌트 추가, 식당 지도 페이지 로딩 기능 구현, 홈으로 버튼 추가
team1codadoc/Vegopa pull request #11
Opened 2022-05-18 16:51 UTC by Seongtaek-H

2022-05-19 05:10 UTC, Luceta commented
git 커밋 메세지 컨벤션 확인해주시면 좋을것 같습니다! 체크표시는 test code add나 update로 알고 있는데 체크표시가 되어있습니다

2022-05-19 05:20 UTC, Luceta requested changes
로딩을 보니 스피너 코드라 생각되어 지는데 , 중복적인 거 같은데 한번 확인 해주시면 좋을거 같아요. 
props 테마에서 가져다 쓰는 것으로 보완해주시면 좋을 것 같습니다.

빠르게 작업하시느라 수고하셨습니다.

2022-05-19 05:20 UTC, Luceta commented on src/components/loading.tsx
> +  color: black;
저희 테마에 검정색이 있는데  props를 활용해주시길 추천드립니다.

2022-05-19 05:20 UTC, Luceta commented on src/components/map.tsx
> +            <a href={selectedPlace.place_url}>
리액트 내에서는 <a> 태그의 href로 이동하면 상태 값을 잃고 속도가 저하되는 점과 눈에는 안 보이지만 살짝 껌뻑 할 수 있어서 Link태그 사용을 권장하는 데, a태그로 하신 이유가 있을까요?

2022-05-19 05:20 UTC, Luceta commented on src/components/map.tsx
> +  background-color: white;
이 부분도 테마를 적극적으로 활용해주세요 props

2022-05-19 05:20 UTC, Luceta commented on src/components/map.tsx
> +  left: 50%;
지금도 무난하지만, 50%가 자주 쓰인다면, theme에 size 파일을만들어서 50% 등록 해놓고 props로 가져다 쓰는 방법도 좋을것 같아요

2022-05-19 05:20 UTC, Luceta commented on src/components/loading.tsx
> +`;
이 코드가 혹시 스피너 부분이라면.. 이미 스피너 컴포넌트가 있는데 그 부분을 활용하시면 될거 같아요 
폴더 트리 한번 확인 부탁드릴께요

2022-05-19 11:13 UTC, wade3420 commented on src/components/map.tsx
> +            level: 5,
오 이건 범위를 늘리신건가요? 변경이유 궁금해요

2022-05-19 11:13 UTC, wade3420 commented on src/components/map.tsx
> +  const [isLoading, setIsLoading] = useState(false);
나중에 이 로직을 품고있는 api요청부분을 따로 커스텀훅으로 구현해서 분리해놔도 좋을 것 같아요

2022-05-19 13:30 UTC, Seongtaek-H commented on src/components/loading.tsx
> +  color: black;
확인요.

2022-05-19 13:31 UTC, Seongtaek-H commented on src/components/map.tsx
> +            <a href={selectedPlace.place_url}>
카카오 지도 외부 링크로 가는 태그라서 Link태그 사용해서 리다이렉트 처리하는 것보다 a 태그 사용해서 간편하게 하는게 더 좋다고 판단했습니다.

2022-05-19 13:31 UTC, Seongtaek-H commented on src/components/map.tsx
> +  background-color: white;
확인요

2022-05-19 13:32 UTC, Seongtaek-H commented on src/components/map.tsx
> +  left: 50%;
다른 페이지에서도 홈버튼을 계속 사용할 여지가 있으면 그런 방법도 괜찮을 것 같습니다.

2022-05-19 13:32 UTC, Seongtaek-H commented on src/components/loading.tsx
> +`;
기존에 있던 스피너로 대체하겠습니다.

2022-05-19 13:33 UTC, Seongtaek-H commented on src/components/map.tsx
> +            level: 5,
level 4로 두니까 지도 범위가 좀 작아서 식당들이 몇개 표시되지도 않고 그래도 식당 정보 주는건데 너무 좁으면 한 눈에 보기 어렵다고 판단했습니다.

2022-05-19 16:56 UTC, Luceta commented on src/components/map.tsx
> +            <a href={selectedPlace.place_url}>
넵 알겠습니다.

2022-05-19 17:00 UTC, Luceta reviewed
재 사용성 부분에 있어서 고민 해보면 좋을 것 같아서 리뷰 남겼습니다. 

수고하셨습니다!

2022-05-19 17:00 UTC, Luceta commented on src/components/map.tsx
> +      )}
이 부분 보니 mbti loading 이랑 구조가 비슷한데 하나 컴포넌트 만들엇거 children으로 타이틀만 바꾸고 props 로 color 2개 넘겨주면, 각 페이지 로딩에 맞게 커스텀화 되면서 재사용성을 높일 수 있을 것 같네요

2022-05-19 17:00 UTC, Luceta commented on src/theme/colors.ts
> +  KaKao_Yellow: string;
`KAKAO_YELLOW:string` 으로 제안해 봅니다. 상수화 이기 때문에 대문자로

2022-05-20 00:20 UTC, Seongtaek-H commented on src/theme/colors.ts
> +  KaKao_Yellow: string;
네 반영할게요

2022-05-20 00:20 UTC, merged